# Generated by Django 5.2.17 on 2026-09-25 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "donor_code",
                    models.CharField(editable=False, max_length=16, unique=True),
                ),
                ("first_name", models.CharField(max_length=60)),
                ("middle_name", models.CharField(blank=True, max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("suffix", models.CharField(blank=True, max_length=10)),
                ("date_of_birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                            ("UNDISCLOSED", "Prefer not to say"),
                        ],
                        max_length=12,
                    ),
                ),
                ("contact_number", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "municipality",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("province", models.CharField(blank=True, max_length=120)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=30),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TEMP_DEFERRED", "Temporarily deferred"),
                            ("PERM_DEFERRED", "Permanently deferred"),
                            ("INACTIVE", "Inactive"),
                            ("BLACKLISTED", "Blacklisted / restricted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=14,
                    ),
                ),
                ("deferral_reason", models.CharField(blank=True, max_length=255)),
                ("deferred_until", models.DateField(blank=True, null=True)),
                ("points_balance", models.IntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="DonorScreening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("identity_verified", models.BooleanField(default=False)),
                ("consent_given", models.BooleanField(default=False)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "bp_systolic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "bp_diastolic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("pulse_bpm", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "hemoglobin_gdl",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("CLEARED", "Cleared"),
                            ("DEFERRED", "Deferred"),
                            ("REJECTED", "Rejected"),
                            ("REQUIRES_REVIEW", "Requires review"),
                        ],
                        default="REQUIRES_REVIEW",
                        max_length=16,
                    ),
                ),
                (
                    "deferral_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Staff-decided temporary deferral length (clinical judgement — not computed by the system).",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="ScreeningQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("category", models.CharField(default="General", max_length=60)),
                (
                    "answer_type",
                    models.CharField(
                        choices=[
                            ("YESNO", "Yes / No"),
                            ("TEXT", "Free text"),
                            ("NUMBER", "Number"),
                            ("CHOICE", "Choices (comma-separated)"),
                        ],
                        default="YESNO",
                        max_length=6,
                    ),
                ),
                (
                    "choices_text",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated options for CHOICE type",
                        max_length=255,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScreeningResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["question__category", "question__order"],
            },
        ),
    ]
