# Generated by Django 5.2.17 on 2026-09-25 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donations", "0002_initial"),
        ("donors", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="blood_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donors",
                to="inventory.bloodtype",
            ),
        ),
        migrations.AddField(
            model_name="donor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="donorscreening",
            name="donation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screening",
                to="donations.donation",
            ),
        ),
        migrations.AddField(
            model_name="donorscreening",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="screenings",
                to="donors.donor",
            ),
        ),
        migrations.AddField(
            model_name="donorscreening",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screenings_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="screeningresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responses",
                to="donors.screeningquestion",
            ),
        ),
        migrations.AddField(
            model_name="screeningresponse",
            name="screening",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="donors.donorscreening",
            ),
        ),
        migrations.AddIndex(
            model_name="donor",
            index=models.Index(
                fields=["status", "blood_type"], name="donors_dono_status_09b1b6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="screeningresponse",
            unique_together={("screening", "question")},
        ),
    ]
