# Generated by Django 4.2.7 on 2026-10-09 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registrationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('felt_well_today', models.BooleanField(null=True, verbose_name='I feel well and healthy today.')),
                ('on_medication', models.BooleanField(null=True, verbose_name='I am currently taking any medication.')),
                ('recent_illness', models.BooleanField(null=True, verbose_name='I have had fever, flu, cold, cough, or infection within the past 2 weeks.')),
                ('prior_transfusion', models.BooleanField(null=True, verbose_name='I have received a blood transfusion at any time in my life.')),
                ('reactive_test', models.BooleanField(null=True, verbose_name='I have ever tested positive for Hepatitis B/C, HIV, Syphilis, or had Malaria.')),
                ('tattoo_piercing', models.BooleanField(null=True, verbose_name='I have had a tattoo, body piercing, or acupuncture within the past 12 months.')),
                ('dental_procedure', models.BooleanField(null=True, verbose_name='I have had a tooth extraction or dental procedure within the past 72 hours.')),
                ('recent_vaccination', models.BooleanField(null=True, verbose_name='I have been vaccinated within the past 4 weeks.')),
                ('high_risk_behavior', models.BooleanField(null=True, verbose_name='Within the past 12 months I have shared needles or had sexual contact with a partner at risk for HIV/Hepatitis.')),
                ('pregnant_or_breastfeeding', models.BooleanField(null=True, verbose_name='I am currently pregnant, breastfeeding, or delivered within the past year.')),
                ('previously_deferred', models.BooleanField(null=True, verbose_name='I have ever been deferred or turned away from donating blood.')),
                ('declaration', models.BooleanField(default=False, verbose_name='I certify that the information above is true and complete to the best of my knowledge, and I understand it will be reviewed by blood bank staff.')),
                ('notes', models.TextField(blank=True, verbose_name='Additional notes (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='accounts.registrationrequest')),
            ],
            options={
                'verbose_name': 'Registration donor interview',
                'verbose_name_plural': 'Registration donor interviews',
            },
        ),
    ]
