# Generated by Django 5.2.17 on 2026-09-25 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "donation_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "donation_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("donation_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "donation_type",
                    models.CharField(
                        choices=[
                            ("VOLUNTARY", "Voluntary"),
                            ("REPLACEMENT", "Replacement"),
                            ("DIRECTED", "Directed"),
                            ("AUTOLOGOUS", "Autologous"),
                        ],
                        default="VOLUNTARY",
                        max_length=12,
                    ),
                ),
                ("volume_ml", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("REGISTERED", "Registered"),
                            ("SCREENING", "Screening"),
                            ("APPROVED", "Approved"),
                            ("COLLECTED", "Collected"),
                            ("TESTING", "Testing"),
                            ("RELEASED", "Released"),
                            ("DEFERRED", "Deferred"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="REGISTERED",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donation",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "ordering": ["-donation_date", "-created_at"],
            },
        ),
    ]
