# Generated by Django 5.2.17 on 2026-09-25 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donations", "0001_initial"),
        ("donors", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="blood_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="inventory.bloodtype",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donations",
                to="donors.donor",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations_recorded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["donor", "status"], name="donations_d_donor_i_d5122b_idx"
            ),
        ),
    ]
