# Generated by Django 5.2.17 on 2026-09-25 17:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donations", "0001_initial"),
        ("donors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("code", models.SlugField(max_length=20, unique=True)),
                (
                    "default_shelf_life_days",
                    models.PositiveIntegerField(
                        help_text="Used to compute expiration from collection time. Institutional value — validate before production."
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TestType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GROUPING", "Blood grouping"),
                            ("RH", "Rh typing"),
                            ("INFECTIOUS", "Infectious-disease screening"),
                            ("OTHER", "Other institutional test"),
                        ],
                        default="OTHER",
                        max_length=12,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Required tests must be completed and acceptable before a bag can be released.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="BloodType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abo",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("AB", "AB"), ("O", "O")],
                        max_length=2,
                    ),
                ),
                (
                    "rh",
                    models.CharField(
                        choices=[("POS", "+"), ("NEG", "−")], max_length=3
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["abo", "rh"],
                "unique_together": {("abo", "rh")},
            },
        ),
        migrations.CreateModel(
            name="BloodBag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bag_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("collected_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("volume_ml", models.PositiveIntegerField(default=450)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Storage facility / fridge",
                        max_length=120,
                    ),
                ),
                ("storage_position", models.CharField(blank=True, max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUARANTINED", "Quarantined"),
                            ("TESTING", "Testing"),
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("ISSUED", "Issued"),
                            ("TRANSFUSED", "Transfused"),
                            ("EXPIRED", "Expired"),
                            ("DISCARDED", "Discarded"),
                            ("RETURNED", "Returned"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="QUARANTINED",
                        max_length=12,
                    ),
                ),
                (
                    "screening_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null only for externally sourced bags registered manually (audited).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blood_bags",
                        to="donations.donation",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blood_bags",
                        to="donors.donor",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="released_bags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bags",
                        to="inventory.bloodcomponent",
                    ),
                ),
                (
                    "blood_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bags",
                        to="inventory.bloodtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at"],
            },
        ),
        migrations.CreateModel(
            name="CompatibilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_allowed", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to apply to all components.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.bloodcomponent",
                    ),
                ),
                (
                    "donor_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compat_as_donor",
                        to="inventory.bloodtype",
                    ),
                ),
                (
                    "patient_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compat_as_patient",
                        to="inventory.bloodtype",
                    ),
                ),
            ],
            options={
                "ordering": ["patient_type__abo", "donor_type__abo"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("COLLECTION", "Collection"),
                            ("QUARANTINE", "Quarantine"),
                            ("TESTING", "Testing"),
                            ("RELEASE", "Authorized release"),
                            ("RESERVATION", "Reservation"),
                            ("ISSUE", "Issue"),
                            ("RETURN", "Return"),
                            ("DISCARD", "Discard"),
                            ("EXPIRATION", "Expiration"),
                            ("ADJUSTMENT", "Adjustment / override"),
                        ],
                        max_length=12,
                    ),
                ),
                ("previous_status", models.CharField(max_length=12)),
                ("new_status", models.CharField(max_length=12)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "reference",
                    models.CharField(
                        blank=True, help_text="e.g. blood request code", max_length=120
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="inventory.bloodbag",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        help_text="Raw result value, e.g. 'O RhD positive'",
                        max_length=120,
                    ),
                ),
                (
                    "result_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("NON_REACTIVE", "Non-reactive / Acceptable"),
                            ("REACTIVE", "Reactive"),
                            ("INVALID", "Invalid"),
                            ("REQUIRES_RETEST", "Requires retest"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="test_results",
                        to="inventory.bloodbag",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tests_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tests_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="inventory.testtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bloodbag",
            index=models.Index(
                fields=["status", "expires_at"], name="inventory_b_status_f2ccfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bloodbag",
            index=models.Index(
                fields=["blood_type", "component", "status"],
                name="inventory_b_blood_t_6956f3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="compatibilityrule",
            unique_together={("patient_type", "donor_type", "component")},
        ),
    ]
