# Generated by Django 5.2.17 on 2026-09-25 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("points_cost", models.PositiveIntegerField()),
                (
                    "stock",
                    models.PositiveIntegerField(
                        blank=True, help_text="Blank = unlimited", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["points_cost"],
            },
        ),
        migrations.CreateModel(
            name="RewardRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=60, unique=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("DONATION_COMPLETED", "Donation completed"),
                            ("EMERGENCY_DONATION", "Emergency donation"),
                            ("MILESTONE", "Milestone donation bonus"),
                            ("REFERRAL", "Referral bonus"),
                            ("EMERGENCY_RESPONSE", "Emergency call response"),
                            ("MANUAL", "Manual adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                (
                    "milestone_every_n",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="For MILESTONE rules: award bonus every N donations.",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["event"],
            },
        ),
        migrations.CreateModel(
            name="RewardTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("min_points", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["min_points"],
            },
        ),
        migrations.CreateModel(
            name="DonorReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_spent", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REDEEMED", "Redeemed"),
                            ("FULFILLED", "Fulfilled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REDEEMED",
                        max_length=10,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rewards",
                        to="donors.donor",
                    ),
                ),
                (
                    "fulfilled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="rewards.reward",
                    ),
                ),
            ],
            options={
                "ordering": ["-redeemed_at"],
            },
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Positive = credit, negative = debit"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EARN", "Earned"),
                            ("REDEEM", "Redemption"),
                            ("BONUS", "Bonus"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Idempotency key, e.g. donation:DN-2026-000001",
                        max_length=120,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("running_balance", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="point_transactions",
                        to="donors.donor",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rewards.reward",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rewards.rewardrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["donor", "reference"],
                        name="rewards_poi_donor_i_3e1378_idx",
                    )
                ],
            },
        ),
    ]
