# Generated by Django 5.2.17 on 2026-09-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="channel",
            field=models.CharField(
                choices=[
                    ("ORGANIZATION", "Organization (requester account)"),
                    ("WALK_IN", "Walk-in at the blood bank"),
                ],
                db_index=True,
                default="ORGANIZATION",
                help_text="WALK_IN: recorded by staff at the counter for a patient who came to the blood bank directly, with no requester account. Never visible to organization requesters.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="walk_in_contact",
            field=models.CharField(
                blank=True,
                help_text="Person at the counter to deal with on a walk-in request (name or role, e.g. patient, relative, referring midwife).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="walk_in_phone",
            field=models.CharField(
                blank=True,
                help_text="Optional callback number for a walk-in request.",
                max_length=30,
            ),
        ),
    ]
