# Generated by Django 5.2.17 on 2026-09-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0002_bloodrequest_channel_bloodrequest_walk_in_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="channel",
            field=models.CharField(
                choices=[
                    ("ORGANIZATION", "Organization (requester account)"),
                    ("WALK_IN", "Walk-in at the blood bank"),
                ],
                db_index=True,
                default="ORGANIZATION",
                help_text="WALK_IN: recorded by staff at the counter for a patient who came to the blood bank directly, with no requester account. A direct clinic request — validated at the counter, never queued for approval, and never visible to organization requesters.",
                max_length=12,
            ),
        ),
    ]
