# Generated by Django 5.2.17 on 2026-09-25 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("donors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="donors.donor",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["CANCELLED", "NO_SHOW", "COMPLETED"]), _negated=True
                ),
                fields=("donor", "date", "time"),
                name="unique_open_appointment_slot",
            ),
        ),
    ]
