# Generated by Django 5.2.17 on 2026-09-25 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=100, unique=True)),
                ("value", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("eligibility", "Donor Eligibility Rules"),
                            ("inventory", "Inventory & Blood Bank"),
                            ("notifications", "Notifications"),
                            ("rewards", "Rewards"),
                            ("security", "Security"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("str", "Text"),
                            ("int", "Number"),
                            ("bool", "Yes/No"),
                        ],
                        default="str",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_sensitive", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "key"],
            },
        ),
    ]
